#!/bin/sh

MONO_PREFIX=/home/nestor/opt/mono
PATH=$MONO_PREFIX/bin:$PATH
REPORT_PATH=./2.0-reports

MONO_ASSEMBLIES=$MONO_PREFIX/lib/mono/2.0

for assembly in $MONO_ASSEMBLIES/*.dll
do
	gendarme --config rules-net_2_0.xml --set net_2_0 $assembly --html $assembly.html
done

mkdir $REPORT_PATH/`date +%m-%d-%Y`
mv $MONO_ASSEMBLIES/*.html $REPORT_PATH/`date +%m-%d-%Y`
